name: Build Optimized Binaries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Make build script executable
        run: chmod +x ./build.sh
        working-directory: ./codeforgeai.go

      - name: Run build script
        run: ./build.sh
        working-directory: ./codeforgeai.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: codeforgeai-binaries
          path: ./codeforgeai.go/build/
